export const films = [
    {
        _id: 0,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: true,
        link: './posters/1.jpg',
    },
    {
        _id: 1,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: true,
        link: './posters/2.jpg',
    },
    {
        _id: 2,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/3.jpg',
    },
    {
        _id: 3,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/4.jpg',
    },
    {
        _id: 4,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/5.jpg',
    },
    {
        _id: 5,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: '../posters/6.jpg',
    },
    {
        _id: 6,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/7.jpg',
    },
    {
        _id: 7,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/8.jpg',
    },
    {
        _id: 8,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/9.jpg',
    },
    {
        _id: 9,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/10.jpg',
    },
    {
        _id: 10,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: true,
        link: './posters/11.jpg',
    },
    {
        _id: 11,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/12.jpg',
    },
    {
        _id: 12,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/1.jpg',
    },
    {
        _id: 13,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/2.jpg',
    },
    {
        _id: 14,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/3.jpg',
    },
    {
        _id: 15,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/4.jpg',
    },
    {
        _id: 16,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/5.jpg',
    },
    {
        _id: 17,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/6.jpg',
    },
    {
        _id: 18,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/7.jpg',
    },
    {
        _id: 19,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/8.jpg',
    },
    {
        _id: 20,
        name: 'В погоне за Бенкси',
        duration: '1ч 27м',
        saved: false,
        link: './posters/9.jpg',
    },
]